---
title: "p8105_hw6_sw3737"
author: "Shiqi Wu"
date: "2023-11-30"
output: github_document
---

```{r setup, include=FALSE}
library(rnoaa)
library(dplyr)
library(ggplot2)
library(broom)
library(tidyverse)
library(boot)
```

# Problem 2

## Download the data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31"
  ) |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10
  ) |>
  select(name, id, everything())
```
## Define the bootstrap function
```{r}
bootstrap_fn <- function(data) {
  sample_df <- data %>% sample_n(nrow(data), replace = TRUE)
  model <- lm(tmax ~ tmin + prcp, data = sample_df)
  tidy_model <- broom::tidy(model)
  glance_model <- broom::glance(model)
  
  beta1_beta2 <- tidy_model$estimate[2] * tidy_model$estimate[3] # coefficients for tmin and PRCP
  r_squared <- glance_model$r.squared
  
  return(c(r_squared, log(beta1_beta2)))
}
```

## Perform bootstrap
```{r}
set.seed(123)
bootstrap_results <- replicate(5000, bootstrap_fn(weather_df))

bootstrap_df <- as.data.frame(t(bootstrap_results))
names(bootstrap_df) <- c("r_squared", "log_beta1_beta2")
```

## Plot the distributions
```{r}
# Plotting the distribution of r_squared
ggplot(bootstrap_df, aes(x = r_squared)) +
  geom_histogram(bins = 30, fill = "lightblue", alpha = 0.7) +
  labs(title = "Distribution of r^2 Estimates", x = "r^2", y = "Frequency")

# Plotting the distribution of log_beta1_beta2
ggplot(bootstrap_df, aes(x = log_beta1_beta2)) +
  geom_histogram(bins = 30, fill = "pink", alpha = 0.7) +
  labs(title = "Distribution of log(beta1 * beta2) Estimates", x = "log(beta1 * beta2)", y = "Frequency")
```

## Calculate and print the 95% confidence intervals
```{r}
# Calculating confidence intervals excluding NaNs
r_squared_ci <- quantile(bootstrap_df$r_squared, c(0.025, 0.975), na.rm = TRUE)
log_beta1_beta2_ci <- quantile(bootstrap_df$log_beta1_beta2, c(0.025, 0.975), na.rm = TRUE)

# Displaying the results
print(paste("95% CI for r^2: ", r_squared_ci))
print(paste("95% CI for log(beta1 * beta2): ", log_beta1_beta2_ci))
```

